Cars/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = (
    [
    path('admin/', admin.site.urls),
    path('', include('brands.urls')),
    path('', include('models.urls')),
    path('', include('users.urls')),



] + static(settings.STATIC_URL, document_url=settings.STATIC_URL)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

)

users/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from .views import  RegisterView, PasswordChangeView
from .views import MyPasswordChangeView, MyPasswordResetDoneView

app_name = 'users'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', RegisterView.as_view(template_name="register.html"), name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('change/', MyPasswordChangeView.as_view(),  name='change_password'),
    path('change_done/', MyPasswordResetDoneView.as_view(), name='change_done'),
    # path('change/', PasswordChangeView.as_view(template_name="registration/account.html"), name='change'),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/add_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Обновлённый комментарий</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Изменить">
    </form>
</body>
</html>

templates/all_brands.html
<!doctype html>
<html lang="en">
<head>
    <title>Все модели</title>
</head>
<body>

<div>
        {% for cars in car %}
    <h2>Название: <a href="{{ cars.id }}">{{ cars.name }}</a></h2>
        {% endfor %}
</div>
</body>
</html>

{#    {% for cars in car %}#}
{#    {% endfor %}#}

templates/all_models.html
<!doctype html>
<html lang="en">
<head>
    <title>Детальное Представление</title>
</head>
<body>

{#{% for shows in shows %}#}
    <div>
{#    <p><img src="{{ show.image.url }}" alt="..."></p>#}
    <h2>Название: {{ shows.name }}</h2>
    <p>Двигатель: {{ shows.engine }}</p>
    <p>Мощьность: {{ shows.hp }}</p>
    <p>Ньютон - метр: {{ shows.nm }}</p>
    <p>Серия : {{ shows.series }}</p>
        <a href="/all_brands/{{shows.id }}/update/">Изменить модель </a>
        <a href="/all_brands/{{shows.id }}/add/">Добавить комментарий </a>
    </div>
<div>

        {% for i in shows.model_comment.all %}
                <h2>Комментарии:</h2><p>{{ i.text }}</p>
    {% endfor %}

            {% for i in shows.model_comment.all %}
              <p>Автор:</p><p>{{ i.author }}</p>
        {% endfor %}
</div>
</body>
</html>

templates/base.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title></title>#}
{#</head>#}
{#<body>#}
{##}
{#{% block content %}#}
{##}
{#{% endblock %}#}
{##}
{#</body>#}
{#</html>#}

templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Выход</title>
</head>
<body>
    <h2>Вы вышли из своей учетной записи</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Войти</a>
        </small>
    </div>
</body>
</html>'

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Профиль</title>
</head>
<body>
    <div class="content-section">
      <div class="media">
        <div class="media-body">
          <h2 class="account-heading">Имя пользователя: {{ user.username }}</h2>
          <p class="text-secondary">Email: {{ user.email }}</p>
        </div>
      </div>
        <a class="nav-item nav-link" href="{% url 'users:change_password' %}">Изменить пароль</a>
    </div>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
                <button class="btn btn-outline-info" type="submit">Регистрация</button>
        </form>
                Уже есть аккаунт? <a class="ml-2" href="registration/login.html">Вход</a>
{#{% if messages %}#}
{#         {% for message in messages %}#}
{#           <div class="alert alert-{{ message.tags }}">#}
{#             {{ message }}#}
{#           </div>#}
{#         {% endfor %}#}
{#{% endif %}#}
</body>
</html>

templates/shows_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SHows Update</title>
</head>
<body>
<h1>Добавить коментарий</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Изменить">
    </form>
</body>
</html>